model_arch: Qwen2.5-VL
stage_args:
 - stage_id: 0
   runtime:
     num_tpus: 1
     max_batch_size: 1
   scheduler: vit
   final_output: false
   scheduler_params: {}
   model_class: Qwen2_5VLVisionModel

 - stage_id: 1
   runtime:
     num_tpus: 1
     max_batch_size: 1
   scheduler: auto_regressive
   scheduler_params: {}
   model_class: Qwen2ForCausalLM
   final_output: true
   # final_output_type: text
