model_arch: Wan-AI/Wan2.1-T2V-1.3B
# how can we mapping model name to stage config yaml and impl class
stage_args:
 - stage_id: 0
   runtime:
     num_tpus: 4
     max_batch_size: 1
   scheduler: auto_regressive
   final_output: true
   scheduler_params: {}
   model_class: UMT5EncoderModel